### ISSUE TITLE
Token access

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-census-platform#1]
Currently authentication to the API endpoints is by Django token access. 
Should this instead with an azure API key?

**Comment by pacharanero** [comment]
The Django authentication has now all been removed as of 
959f8579690d0605f01d528b6326b3ee7409c19b
4162f1babe80712ed1c0e887d3a19b63e45b500d
0175704952ed623d98dc3db20e65ebff27c00299

**Comment by pacharanero** [comment]
The API is mounted behind the APIM on Azure and API keys can be generated by creating accounts in the RCPCH Dev portal. For utility/service accounts (eg for E12 internal use) these API keys can be manually set in the Azure APIM admin portal to have unlimited quota, no rate limits, etc.
