### ISSUE TITLE
Add organisation and gp practice lists

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-census-platform#20]
The RCPCH Census Platform should have a curated list of:
1. all organisations in the UK where children are cared for (hospitals both acute and community)
2. the relationships of these organisations with their parent (eg trust or health board)
3. the relationships of this organisations with their ICB or NHS region
4. their relationships with other paediatric organisational units (eg PZ number for diabetes centres, OPEN UK region for epilepsy etc)
5. The organisations should contain the ODS code as the national standard
6. The organisation list should be versioned and kept current against the spineservices API, bumping the version when a merger takes place and storing the date
7. The same potentially could be done for all GP practices

This means in addition to a database back end it would need some kind of scheduling element, such as celery beat.

This service would be a further dependency for other RCPCH projects, such as NPDA and Epilepsy12

**Comment by mbarton** [comment]
Implemented as a separate service: https://github.com/rcpch/rcpch-nhs-organisations
