### ISSUE TITLE
ERROR in Azure web app log stream likely requires schema change

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-census-platform#6]
Encountered 2 components with identical names "Nested" and different classes <class 'rest_framework.serializers.ModelSerializer.build_nested_field.<locals>.NestedSerializer'> and <class 'rest_framework.serializers.ModelSerializer.build_nested_field.<locals>.NestedSerializer'>. This will very likely result in an incorrect schema. Try renaming one.

**Comment by anchit-chandran** [comment]
should be fixed with PR, related to #15
